import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface BlueprintRequest {
  projectId: string;
  buildingType: string;
  landWidth: number;
  landLength: number;
  floors: number;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization")! },
        },
      }
    );

    const { projectId, buildingType, landWidth, landLength, floors }: BlueprintRequest =
      await req.json();

    console.log("Generating blueprint for project:", projectId);

    // Call Lovable AI to generate blueprint layout
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const prompt = `You are an expert architect. Generate a detailed building floor plan layout in JSON format.

Building specifications:
- Type: ${buildingType}
- Land dimensions: ${landWidth}m x ${landLength}m
- Number of floors: ${floors}

Create a JSON object with the following structure:
{
  "totalArea": number (in square meters),
  "rooms": [
    {
      "id": string,
      "type": string (e.g., "living_room", "bedroom", "kitchen", "bathroom", "office", "corridor"),
      "width": number (in meters),
      "length": number (in meters),
      "area": number (in square meters),
      "position": { "x": number, "y": number }
    }
  ],
  "doors": [
    { "from": string (room id), "to": string (room id), "position": { "x": number, "y": number } }
  ],
  "windows": [
    { "roomId": string, "wall": string ("north"|"south"|"east"|"west"), "count": number }
  ]
}

Design principles:
1. For a ${buildingType}, include appropriate rooms (e.g., for a house: living room, bedrooms, kitchen, bathrooms)
2. Ensure total room area doesn't exceed 80% of land area (${landWidth * landLength * 0.8}m²)
3. Use standard room dimensions appropriate for the building type
4. Position rooms logically with proper circulation space
5. Include corridors for access between rooms
6. Place bathrooms and kitchen near plumbing lines
7. Ensure adequate natural lighting with windows

Return ONLY valid JSON, no additional text or markdown.`;

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: "You are an expert architect that generates building blueprints in JSON format.",
          },
          { role: "user", content: prompt },
        ],
        temperature: 0.7,
      }),
    });

    if (!aiResponse.ok) {
      if (aiResponse.status === 429) {
        throw new Error("Rate limit exceeded. Please try again later.");
      }
      if (aiResponse.status === 402) {
        throw new Error("AI credits exhausted. Please add credits to continue.");
      }
      const errorText = await aiResponse.text();
      console.error("AI gateway error:", aiResponse.status, errorText);
      throw new Error("Failed to generate blueprint with AI");
    }

    const aiData = await aiResponse.json();
    const blueprintText = aiData.choices?.[0]?.message?.content;

    if (!blueprintText) {
      throw new Error("No blueprint generated by AI");
    }

    console.log("AI Response:", blueprintText);

    // Parse JSON from AI response (remove markdown code blocks if present)
    let blueprintJson;
    try {
      const jsonMatch = blueprintText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        blueprintJson = JSON.parse(jsonMatch[0]);
      } else {
        blueprintJson = JSON.parse(blueprintText);
      }
    } catch (e) {
      console.error("Failed to parse AI response:", blueprintText);
      throw new Error("Invalid JSON in AI response");
    }

    // Generate simple SVG representation
    const svgData = generateSVG(blueprintJson, landWidth, landLength);

    // Store blueprint in database
    const { error: insertError } = await supabaseClient.from("blueprints").insert({
      project_id: projectId,
      blueprint_json: blueprintJson,
      svg_data: svgData,
    });

    if (insertError) throw insertError;

    return new Response(
      JSON.stringify({ success: true, blueprint: blueprintJson }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in generate-blueprint:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});

function generateSVG(blueprint: any, landWidth: number, landLength: number): string {
  const scale = 20; // pixels per meter
  const width = landWidth * scale;
  const height = landLength * scale;
  const padding = 40;

  let svg = `<svg width="${width + padding * 2}" height="${height + padding * 2}" xmlns="http://www.w3.org/2000/svg">`;
  
  // Background
  svg += `<rect x="${padding}" y="${padding}" width="${width}" height="${height}" fill="#f8f9fa" stroke="#333" stroke-width="3"/>`;

  // Draw rooms
  if (blueprint.rooms) {
    blueprint.rooms.forEach((room: any) => {
      const x = padding + (room.position?.x || 0) * scale;
      const y = padding + (room.position?.y || 0) * scale;
      const w = room.width * scale;
      const h = room.length * scale;

      // Room rectangle
      svg += `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#e3f2fd" stroke="#1976d2" stroke-width="2"/>`;
      
      // Room label
      const labelX = x + w / 2;
      const labelY = y + h / 2;
      svg += `<text x="${labelX}" y="${labelY}" text-anchor="middle" font-family="Arial" font-size="12" fill="#333">${room.type.replace(/_/g, " ")}</text>`;
      svg += `<text x="${labelX}" y="${labelY + 15}" text-anchor="middle" font-family="Arial" font-size="10" fill="#666">${room.area.toFixed(1)}m²</text>`;
    });
  }

  // Draw doors
  if (blueprint.doors) {
    blueprint.doors.forEach((door: any) => {
      const x = padding + (door.position?.x || 0) * scale;
      const y = padding + (door.position?.y || 0) * scale;
      svg += `<line x1="${x}" y1="${y}" x2="${x + 15}" y2="${y}" stroke="#ff6b6b" stroke-width="3"/>`;
      svg += `<circle cx="${x}" cy="${y}" r="3" fill="#ff6b6b"/>`;
    });
  }

  // Legend
  svg += `<text x="${padding}" y="${padding - 15}" font-family="Arial" font-size="14" font-weight="bold" fill="#333">Floor Plan - ${landWidth}m × ${landLength}m</text>`;

  svg += `</svg>`;
  return svg;
}
